version: '3'

services:
  alice:
    container_name: alice
    image: thierrysans/alice:ssl-stripping
    networks:
      legitimate:
        ipv4_address: 10.0.0.2
    cap_add:
      - NET_ADMIN
    extra_hosts:
      - "sec-commerce.seclab.space:142.1.97.172"

  mallory:
      image: thierrysans/mallory:ssl-stripping
      container_name: mallory
      tty: true
      restart: always
      cap_add:
        - NET_ADMIN
        - SYS_ADMIN
      volumes:
          - .:/shared
      networks:
        legitimate:
          ipv4_address: 10.0.0.3
        malicious:
          ipv4_address: 10.0.1.3
      extra_hosts:
      - "sec-commerce.seclab.space:142.1.97.172"
  
  wireshark:
    image: thierrysans/wireshark:malicious-gateway
    container_name: wireshark
    tty: true
    network_mode: service:alice

networks:
  legitimate:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
  malicious:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
