version: '3'

services:
    
  alice:
      image: thierrysans/alice:remote-code-execution
      container_name: alice
      tty: true
      restart: always
      networks:
        internal:
          ipv4_address: 10.0.0.2
      cap_add:
        - NET_ADMIN
        - SYS_ADMIN
        
  mallory:
      image: thierrysans/mallory:remote-code-execution
      container_name: mallory
      tty: true
      cap_add:
        - NET_ADMIN
      volumes:
          - .:/shared
      networks:
        internal:
          ipv4_address: 10.0.0.3

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
